format = """
(#FF79C6)\
$os\
$username\
[](bg:#ff5555 fg:#6272a4)\
$directory\
[](fg:#ff5555 bg:#ffb86c)\
$git_branch\
$git_status\
[](fg:#ffb86c bg:#f1fa8c)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#f1fa8c bg:#50fa7b)\
$docker_context\
[](fg:#50fa7b bg:#bd93f9)\
$time\
[ ](fg:#bd93f9)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#6272a4"
style_root = "bg:#6272a4"
format = '[ $user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#bd93f9"
disabled = true # Disabled by default

[directory]
style = "bg:#ff5555"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#f1fa8c"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#50fa7b"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#f1fa8c"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#f1fa8c"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#ffb86c"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#ffb86c"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#f1fa8c"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#f1fa8c"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#f1fa8c"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#f1fa8c"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#f1fa8c"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#f1fa8c"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#f1fa8c"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#f1fa8c"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#bd93f9"
format = '[ ♥ $time ]($style)'
