width: 400
notification:
  modifications:
  - match:
        {}
    modify:
      transient: false
      timeout: 7777
      remove-actions: true
  - match:
      app-name: "Spotify"
    modify:
      image-size: 80
      timeout: 1
      send-noti-closed: true
      class-name: "Spotify"
      action-icons: true
      actions:
        - previous
        - media-skip-backward
        - play
        - media-playback-start
        - next
        - media-skip-forward
      action-commands:
        play: playerctl play-pause
        previous: playerctl previous
        next: playerctl next
  

